on:
  push:
    tags:
      # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'v*'

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build jar
        run: |
          javac -d . src/org/tls/*
          jar cmf src/META-INF/MANIFEST.MF TinyOSRS.jar org
          jar tf TinyOSRS.jar

      - name: Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: TinyOSRS.jar
