on:
  push:
    tags:
      # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'v*'

name: Upload Release Asset

jobs:
  build:
    name: Create Release Assets
    runs-on: ubuntu-latest

    # release for each LTS jdk
    strategy:
      matrix:
        java: ['8', '11', '17']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Build jar
        run: |
          javac -d . src/org/tls/*
          jar cmf src/META-INF/MANIFEST.MF TinyOSRS_jdk${{ matrix.java }}.jar org
          jar tf TinyOSRS_jdk${{ matrix.java }}.jar

      - name: Upload jar
        uses: actions/upload-artifact@v2.2.4
        with:
          name: TinyOSRS_jdk${{ matrix.java }}
          path: TinyOSRS_jdk${{ matrix.java }}.jar

  release:
    name: Upload Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download jars
        uses: actions/download-artifact@v2
        with:
          path: /opt/artifacts

      - name: Display structure of downloaded files
        run: ls -R /opt/artifacts

      - name: Release
        uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          artifacts: "*.jar"
          artifactContentType: application/java-archive
          token: ${{ secrets.GITHUB_TOKEN }}
